// Autor: JeanCarloEM.com
// Site do Autor: https://jeancarloem.com
// Repositorio: https://github.com/jcempro/agents.md
// Licenca: Mozilla Public License 2.0
// Site da Licenca: https://www.mozilla.org/MPL/2.0/
// Resumo da Licenca: uso, copia, modificacao e distribuicao permitidos conforme os termos da MPL-2.0.
// Disclaimer: fornecido AS IS, sem garantias de qualquer tipo.
// Gerado de: src/.ia.rules/core/runtime/scripts/long-running.ts; TypeScript 7.0.2 + esbuild 0.28.1; Node 24+.

const F=require("child_process"),L=require("crypto"),o=require("fs"),h=require("os"),M=require("path");function b(t,r){if(!t.length)return 0;const e=[...t].map(Number).filter(Number.isFinite).sort((n,s)=>n-s);return e[Math.min(e.length-1,Math.max(0,Math.ceil(e.length*r)-1))]||0}function x(t,r={}){const e=Number.isFinite(r.margin)?r.margin:.5,n=Number.isFinite(r.minimumMs)?r.minimumMs:1e3,s=Number.isFinite(r.maximumMs)?r.maximumMs:36e5,a=b(t,.95)||n;return Math.min(s,Math.max(n,Math.ceil(a*(1+e))))}function g(t,r){o.mkdirSync(M.dirname(t),{recursive:!0});const e=`${t}.tmp-${process.pid}-${L.randomBytes(3).toString("hex")}`;o.writeFileSync(e,`${JSON.stringify(r,null,2)}
`,{encoding:"utf8",flag:"wx"}),o.renameSync(e,t)}function w(t,r=[],e={}){const n=new Date().toISOString(),s=Date.now(),a=e.statePath,S=e.timeoutMs||x(e.history||[]),N={schema:"agents-long-run/v1",command:t,args:r,startedAt:n,timeoutMs:S,environment:{platform:h.platform(),release:h.release(),arch:h.arch(),node:process.version},status:"running"};return a&&g(a,N),new Promise((v,P)=>{const u=F.spawn(t,r,{cwd:e.cwd||process.cwd(),env:e.env||process.env,shell:!1,stdio:e.stdio||"ignore",windowsHide:!0});let y=!1;const l=(i,c,f)=>{if(y)return;y=!0,clearTimeout(E),e.signal&&e.signal.removeEventListener("abort",d);const m={...N,status:i,exitCode:Number.isInteger(c)?c:null,endedAt:new Date().toISOString(),durationMs:Date.now()-s};f&&(m.error=f.message||String(f)),a&&g(a,m),i==="completed"?v(m):P(Object.assign(new Error(`LONG_RUN_${i.toLocaleUpperCase("en-US")}`),{result:m}))},d=()=>{u.kill(),l("cancelled",null)},E=setTimeout(()=>{u.kill(),l("timed_out",null)},S);u.once("error",i=>l("failed",null,i)),u.once("exit",(i,c)=>l(i===0?"completed":"failed",i,c?new Error(`signal:${c}`):void 0)),e.signal&&(e.signal.aborted?d():e.signal.addEventListener("abort",d,{once:!0}))})}function O(t,r=[],e={}){if(!e.statePath||!o.existsSync(e.statePath))return w(t,r,e);const n=JSON.parse(o.readFileSync(e.statePath,"utf8"));return n.status==="completed"&&n.command===t&&JSON.stringify(n.args)===JSON.stringify(r)?Promise.resolve({...n,resumed:!1,reused:!0}):w(t,r,{...e,history:[...e.history||[],n.durationMs].filter(Number.isFinite)}).then(s=>({...s,resumed:!0,previousStatus:n.status}))}async function p(t=process.argv.slice(2)){const r=t.indexOf("--");if(r<1)throw new Error("Uso: long-running <state.json> -- <comando> [args]");const e=M.resolve(t[0]),n=t[r+1];if(!n)throw new Error("LONG_RUN_COMANDO_AUSENTE");const s=await O(n,t.slice(r+2),{statePath:e,stdio:"inherit"});console.log(JSON.stringify(s))}require.main===module&&p().catch(t=>{console.error(t.message),process.exitCode=1});module.exports={deriveTimeout:x,percentile:b,resumeLongProcess:O,runLongProcess:w,writeState:g};
